### ISSUE TITLE
Touchsrceen does not work

### ISSUE THREAD

**Issue by alkabal** [UnfinishedBusiness/Xmotion#2]
Hi

I have try you fresh release and work really better on my setup (BBB lathe with Furaday cape)

But i have never see my touchscreen working for now, can you help for this ?

Terminal report print :
Found Device: /dev/input/by-id/usb-ILITEK_Multi-Touch-V3000-if01-event-mouse
  Opened device!

Br

**Comment by alkabal** [comment]
Finally i'm not sure if you manage toochscreen or not, i think i have read this somewhere but not sure.

Br

**Comment by UnfinishedBusiness** [comment]
@alkabal - I have not tested with a touchscreen but it should be compatible with any touchscreen that emulates a mouse device. Sorry for the late reply on your issues, I did not get notifications on them. I'll pay closer attention to them for now on

**Comment by alkabal** [comment]
Hi


Many thanks for reply 

I think it’s a multitouch so unfortunately I think it’s not mouse emulation 


Br
